### ISSUE TITLE
problems using official foo_playcount and it's rating

### ISSUE THREAD

**Issue by WebSkater** [TheQwertiest/foo_spider_monkey_panel#59] opened 2019-02-12 14:06 UTC
Hi,
after installing Spider Monkey Panel in perfect working fb2k v1.3.20 on W7 x64 - and not making any use of it, i only installed it - I can't write rating tags to foo_playcount's database anymore. Modifying already existing rating tags stored in the database isn't possible either. Writing rating tags direct to files is still working. After uninstalling Spider Monkey Panel everything is working as before and writing and modifying rating tags in files or in the database is possible again without any issue !

Seems Spider Monkey Panel and the official Playback Statistics (foo_playcount) can't work together without making trouble.

Any ideas or suggestion?

**Comment by TheQwertiest** [comment] 2019-02-12 14:33
Thanks for the bug report!
Which version of SMP are you using? And how are you modifying rating tags?

**Comment by WebSkater** [comment] 2019-02-12 14:44
Hi,
using SMP 1.15. Rating tags are set within a perfect working old skin (Br3tt's kameleon). TIM (foo_uie_trackinfo_mod 0.8.0 beta) is used for the rating part, using "kameleon_rate_to_db" (value 0 or 1) as extended variable (foo_exvar 0.5.0) to switch between writing tags to database or files.

Here's the used script:

$puts(config_name,'kameleon')
$puts(foo_path,%FOOBAR_PATH%)
$puts(img,$get(foo_path)'images/'$get(config_name))

// PerSecond
//$drawrect(0,0,%_width%,%_height%,brushcolor-20-20-20 pencolor-null)

// PerTrack

// ----------------------------
// .deb --- Rating System
// ----------------------------

$if($stricmp('FOO_LASTFM',$left(%path%,10)),
	$imageabs2(0,0,0,0,0,0,0,1,$get(img)'/rating/set1/r0.png',alpha-135)
,

// --------------------------------------------
// drawing RATING info
// --------------------------------------------
//$if(%_isplaying%,

	$puts(aa-fp,$year(%first_played%))
	$puts(mm-fp,$month(%first_played%))
	$puts(jj-fp,$day_of_month(%first_played%))
	$puts(aa-lp,$year(%last_played%))
	$puts(mm-lp,$month(%last_played%))
	$puts(jj-lp,$day_of_month(%last_played%))

   $ifgreater($if3(%rating%,$meta(rating),0),0,
	$puts(rating,$if3(%rating%,$meta(rating),0))
	$puts(no.set,1)
   ,

	$ifgreater($get(aa-lp),$get(aa-fp),
		$ifgreater($get(mm-lp),$get(mm-fp),
			$puts(nb.aa,$sub($get(aa-lp),$get(aa-fp)))
			$puts(nb.mm,$sub($get(mm-lp),$get(mm-fp)))

			$ifgreater($get(jj-lp),$get(jj-fp),
				$puts(nb.jj,$sub($get(jj-lp),$get(jj-fp)))
			,
				$puts(nb.mm,$sub($get(nb.mm),1))
				$puts(nb.jj,$add($sub(30,$get(jj-fp)),$get(jj-lp)))	
			)

		,
			$puts(nb.aa,$sub($sub($get(aa-lp),$get(aa-fp)),1))
			$puts(nb.mm,$add($sub(12,$get(mm-fp)),$get(mm-lp)))

			$ifgreater($get(jj-lp),$get(jj-fp),
				$puts(nb.jj,$sub($get(jj-lp),$get(jj-fp)))
			,
				$puts(nb.mm,$sub($get(nb.mm),1))
				$puts(nb.jj,$add($sub(30,$get(jj-fp)),$get(jj-lp)))	
			)
		)
	,
		$puts(nb.aa,0)
		$ifgreater($get(mm-lp),$get(mm-fp),
			$puts(nb.mm,$sub($get(mm-lp),$get(mm-fp)))
		,
			$puts(nb.mm,0)
		)
		$ifgreater($get(jj-lp),$get(jj-fp),
			$puts(nb.jj,$sub($get(jj-lp),$get(jj-fp)))
		,
			$puts(nb.jj,0)	
		)

	)

	$puts(autorate.add,2)
	$puts(autorate.nbdays.sub,30)

	$puts(daterange, $add( $add($mul(365,$get(nb.aa)),$mul(30,$get(nb.mm))),$get(nb.jj)) )
          
	$puts(fix,$div($get(daterange),$get(autorate.nbdays.sub)))
	$if(%play_counter%,$puts(rating,$div(%play_counter%,$get(autorate.add))),$puts(rating,0))
	$puts(rating,$sub($get(rating),$get(fix)))
	$if($greater($get(rating),5),$puts(rating,5))
	$if($greater(0,$get(rating)),$puts(rating,0))
	$puts(no.set,2)
   )
//,)

$ifgreater($if3(%rating%,$meta(rating),0),0,

  $puts(rate.x,0)
  $puts(rate.y,1)

  $imageabs2(0,0,0,0,0,0,$get(rate.x),$get(rate.y),$get(img)'/rating/set'$get(no.set)'/r0.png',alpha-128)
  $if(%_isplaying%,

	$ifequal($get(rating),1,
		$button($get(rate.x),$get(rate.y),0,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set'$get

(no.set)'/r1x.png',$ifequal(%kameleon_rate_to_db%,1,<not set>,TAG:REMOVE:rating:1),TOOLTIP:"Reset")
	,
		$button($get(rate.x),$get(rate.y),0,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set'$get

(no.set)'/r1.png',$ifequal(%kameleon_rate_to_db%,1,1,TAG:SET:rating:1),TOOLTIP:"Average")
	)
	$ifequal($get(rating),2,
		$button($get(rate.x),$get(rate.y),12,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set'$get

(no.set)'/r2x.png',$ifequal(%kameleon_rate_to_db%,1,<not set>,TAG:REMOVE:rating:2),TOOLTIP:"Reset")
	,
		$button($get(rate.x),$get(rate.y),12,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set'$get

(no.set)'/r2.png',$ifequal(%kameleon_rate_to_db%,1,2,TAG:SET:rating:2),TOOLTIP:"Good")
	)
	$ifequal($get(rating),3,
		$button($get(rate.x),$get(rate.y),24,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set'$get

(no.set)'/r3x.png',$ifequal(%kameleon_rate_to_db%,1,<not set>,TAG:REMOVE:rating:3),TOOLTIP:"Reset")
	,
		$button($get(rate.x),$get(rate.y),24,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set'$get

(no.set)'/r3.png',$ifequal(%kameleon_rate_to_db%,1,3,TAG:SET:rating:3),TOOLTIP:"Very Good")
	)
	$ifequal($get(rating),4,
		$button($get(rate.x),$get(rate.y),36,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set'$get

(no.set)'/r4x.png',$ifequal(%kameleon_rate_to_db%,1,<not set>,TAG:REMOVE:rating:4),TOOLTIP:"Reset")
	,
		$button($get(rate.x),$get(rate.y),36,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set'$get

(no.set)'/r4.png',$ifequal(%kameleon_rate_to_db%,1,4,TAG:SET:rating:4),TOOLTIP:"Excellent")
	)
	$ifequal($get(rating),5,
		$button($get(rate.x),$get(rate.y),48,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set'$get

(no.set)'/r5x.png',$ifequal(%kameleon_rate_to_db%,1,<not set>,TAG:REMOVE:rating:5),TOOLTIP:"Reset")
	,
		$button($get(rate.x),$get(rate.y),48,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set'$get

(no.set)'/r5.png',$ifequal(%kameleon_rate_to_db%,1,5,TAG:SET:rating:5),TOOLTIP:"MegaHit")
	)
  )

,

  $puts(rate.x,0)
  $puts(rate.y,1)

  //$imageabs2(0,0,0,0,0,0,$get(rate.x),$get(rate.y),'./images/ibiza/rating/set'$get(no.set)'/r0.png',alpha-128)

  $if(%isplaying%,
		$button($get(rate.x),$get(rate.y),0,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set1/r1.png',

$ifequal(%kameleon_rate_to_db%,1,1,TAG:SET:rating:1),TOOLTIP:"Average")

		$button($get(rate.x),$get(rate.y),12,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set1/r2.png',

$ifequal(%kameleon_rate_to_db%,1,2,TAG:SET:rating:2),TOOLTIP:"Good")

		$button($get(rate.x),$get(rate.y),24,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set1/r3.png',

$ifequal(%kameleon_rate_to_db%,1,3,TAG:SET:rating:3),TOOLTIP:"Very Good")

		$button($get(rate.x),$get(rate.y),36,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set1/r4.png',

$ifequal(%kameleon_rate_to_db%,1,4,TAG:SET:rating:4),TOOLTIP:"Excellent")

		$button($get(rate.x),$get(rate.y),48,0,12,12,$get(img)'/rating/set'$get(no.set)'/r'$get(rating)'.png',$get(img)'/rating/set1/r5.png',

$ifequal(%kameleon_rate_to_db%,1,5,TAG:SET:rating:5),TOOLTIP:"MegaHit")

  ,

    $imageabs2(0,0,0,0,0,0,$get(rate.x),$get(rate.y),$get(img)'/rating/set'$get(no.set)'/r0.png',alpha-135)

  )

)

)
// ----------------------------
// .fin --- Rating System
// ----------------------------

// MOOD TAG SET/UNSET to feed automatically auto-playlist for my iPod or iPhone
$if($stricmp('FOO_LASTFM',$left(%path%,10)),
	$imageabs2(12,12,0,0,0,0,61,1,$get(img)'/bt/mood0.png',nokeepaspect)
,
	$ifgreater($if2(%MOOD%,0),0,
		$button(61,1,0,0,12,12,$get(img)'/bt/mood1.png',$get(img)'/bt/mood0.png',TAG:REMOVE:MOOD:1,TOOLTIP:"Unset")
	,
		$button(61,1,0,0,12,12,$get(img)'/bt/mood0.png',$get(img)'/bt/mood1.png',TAG:SET:MOOD:1,TOOLTIP:"Set")
	)
)

// SKIP TAG SET/UNSET
$if($stricmp('FOO_LASTFM',$left(%path%,10)),
	$imageabs2(12,12,0,0,0,0,75,2,$get(img)'/bt/skip0.png',nokeepaspect)
,
	$ifgreater($if2(%SKIP%,0),0,
		$button(75,2,0,0,12,12,$get(img)'/bt/skip1.png',$get(img)'/bt/skip0.png',TAG:REMOVE:SKIP:1,TOOLTIP:"Unset")
	,
		$button(75,2,0,0,12,12,$get(img)'/bt/skip0.png',$get(img)'/bt/skip1.png',TAG:SET:SKIP:1,TOOLTIP:"Set")
	)
)

**Comment by TheQwertiest** [comment] 2019-02-12 14:47
Uhm... Did you close by accident? Or was your problem resolved?

**Comment by WebSkater** [comment] 2019-02-12 14:57
Sorry, yes was an accident,

**Comment by WebSkater** [comment] 2019-02-12 14:58
Reopened, because closed by accident.

**Comment by marc2k3** [comment] 2019-02-13 06:29
I'm guessing it's because your $button commands are ambiguous. It's looks like it's set to run a menu command matching 1, 2,3,4 or 5. It doesn't even appear to distinguish between main menu commands and context menu commands?? This is where the conflict comes in because SMP has  main menu commands from 1-10. I'm assuming `Rating/1` etc would work but I've not tested it.

**Comment by TheQwertiest** [comment] 2019-02-13 11:31
>It's looks like it's set to run a menu command matching 1, 2,3,4 or 5

@marc2k3 : yep, you are right - `on_main_menu` callback is invoked when `foo_uie_trackinfo_mod` is utilized this way.

@WebSkater : this is a bug/flaw of `foo_uie_trackinfo_mod` component: it does not provide a way to invoke a command via full path (e.g. `Playback Statistics/Rating/1`) and there is no way to differentiate between *shortened* commands (just `1` in your case). See the corresponding post from the component developer: https://hydrogenaud.io/index.php/topic,47044.msg466220.html#msg466220

Closing the issue, since this is not a bug in `foo_spider_monkey_panel`.

**Closed by TheQwertiest** 2019-02-13 11:31 UTC
