### ISSUE TITLE
Web look-ups seem to be failing as sites remove internet explorer support

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#136] opened 2021-03-31 17:22 UTC
I re-added web look-up to yttm. All was working fine for a long time, then suddenly started getting;

this.xmlhttp.readyState 4
this.xmlhttp.status 0
youtube N/A: Status error: 0

It's failing right on the initial look-up. Normally, yt would at least send an xmlhttp.responseText if rate limiting etc is exceeded.

So it looks as though internet explorer is immediately being detected & the call rejected with a Status error: 0. There may be other explanations, but that seems the most likely. I tried using modern browser user agents to no avail.

Currently, lastfm haven't switched off accepting internet explorer, although say it's unsupported. So it may effect lastfm et al in due course.

Are there any workarounds that you or anybody else reading this know of? Or do SMP methods need updating?

Below is some test code. It would also be useful to know if the issue is reproducible on devices other than my own.

```
class YoutubeSearch {
	constructor(state_callback, on_search_done_callback) {
		this.func = null; this.on_search_done_callback = on_search_done_callback; this.ready_callback = state_callback; this.xmlhttp = null;
	}

    onStateChange() {
        if (this.xmlhttp != null && this.func != null)
			if (this.xmlhttp.readyState == 4) {
				console.log('this.xmlhttp.readyState',this.xmlhttp.readyState);
				console.log('this.xmlhttp.status',this.xmlhttp.status);
				if (this.xmlhttp.status == 200) this.func();
				else {console.log('youtube N/A: ' + (this.xmlhttp.responseText || 'Status error: ' + this.xmlhttp.status));}
			}
    }

    search() {
		//let URL = 'https://www.youtube.com/results?search_query=Black%20Sabbath%20The%20Wizard&sp=EgIQAQ%253D%253D';
		const artist = 'Madonna';
		const title = 'Music';
		const URL = 'https://www.youtube.com/results?search_query=' + encodeURIComponent(artist + ' ' + title);
        this.func = null; this.xmlhttp = new ActiveXObject('Microsoft.XMLHTTP');

		console.log('URL',URL)
        this.func = this.analyse; this.xmlhttp.open('GET', URL); this.xmlhttp.onreadystatechange = this.ready_callback;
		/*edge User-Agent*///this.xmlhttp.setRequestHeader('User-Agent', "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36 Edg/84.0.522.59Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.63");
		/*google referer*///this.xmlhttp.setRequestHeader('Referer', "https://www.google.com/");
		this.xmlhttp.send();
		//https://www.youtube.com/results?search_query=madonna+-+erotica
    }

    analyse() {
		console.log('this.xmlhttp.responseText'+this.xmlhttp.responseText)
		
	}
	
}

const yt = new YoutubeSearch(() => yt.onStateChange(), null); // callback unused in test & set to null
yt.search();

```

**Comment by TheQwertiest** [comment] 2021-04-09 12:59
Not sure if it's fixable. AFAIK Microsoft did not provide any COM/ActiveXObject accessible alternative.
I'll take a look if there any alternatives, but I really don't want to implement the whole browser in SMP (and I won't) .

**Comment by TheQwertiest** [comment] 2021-04-12 10:28
`(MSXML) will not be implemented in any version of Microsoft Edge.` Source: https://docs.microsoft.com/en-us/openspecs/ie_standards/ms-iedoco/638b52a6-c5a1-433d-b872-ca07b8f06bdd

So yeah, there's that.

**Comment by kbuffington** [comment] 2021-05-25 19:23
I tested this and it works just fine for me using the example URLs in wil's code snippet.

**Comment by kbuffington** [comment] 2021-05-25 19:34
Also:

> `(MSXML) will not be implemented in any version of Microsoft Edge.` Source: https://docs.microsoft.com/en-us/openspecs/ie_standards/ms-iedoco/638b52a6-c5a1-433d-b872-ca07b8f06bdd

Pretty sure that's referring to the built in IE XML _parser_ and not the code that allows an XHR. XHR isn't going to go away even if IE is (Edge would instantly break millions of legacy websites that rely on XHR calls). I guess there'd be some slight concern that `Microsoft.XMLHTTP` might cease to exist, but honestly that seems like such a breaking change too that I can't imagine it happening. 

I don't believe there's anything to do for this, and recommend it be closed as not-a-bug although it'd be awesome if we could use `fetch` instead!

**Comment by Wil-B** [comment] 2021-05-25 22:05
I kind of assumed that because TheQwertiest said 'Not sure if it's fixable' he had tested the code and also seen the issue???

I still see this result:
this.xmlhttp.readyState 4
this.xmlhttp.status 0
youtube N/A: Status error: 0

Did you do anything to get it to work? Or possibly things are different in USA or with your set-up in some way?

I tried:
1) Setting 'Let Internet Explorer open sites in Microsoft Edge'  to Never
2) Setting internet explorer (11) to default browser

The search through SMP still gives this.xmlhttp.status 0 and I don't get any xmlhttp.responseText. Tried on 3 fb2k installs.

Anyway I did find a different URL & method that allows me to do what I wanted. So for the time being I have a workaround.

**Comment by kbuffington** [comment] 2021-05-25 22:20
This is the code I used from Georgia which seems pretty similar to yours:

```
function makeHttpRequest(type, url, successCB) {
	/** @type {*} */
	var xmlhttp = new ActiveXObject('Microsoft.XMLHTTP');
	xmlhttp.open(type, url, true);
	xmlhttp.setRequestHeader('User-Agent', 'foo_spider_monkey_georgia');
	xmlhttp.send();
	xmlhttp.onreadystatechange = () => {
		if (xmlhttp.readyState == 4) {
			successCB(xmlhttp.responseText);
		}
	};
}

makeHttpRequest('GET', 'https://www.youtube.com/results?search_query=Black%20Sabbath%20The%20Wizard&sp=EgIQAQ%253D%253D', 
    resp => console.log(resp.substr(0,250)));
```

And this is the result:
```
<!DOCTYPE html><html style="font-size: 10px;font-family: Roboto, Arial, sans-serif;" lang="en" typography typography-spacing><head><meta http-equiv="X-UA-Compatible" content="IE=edge"/><script nonce="OAJSXizSw9apdBThF1vjIw">var ytcfg={d:function(){re...
```

**Comment by kbuffington** [comment] 2021-05-25 22:34
I'm getting the same results with your code as well. It's the user agent. Maybe don't try and impersonate another browser and just give it a string for your script?

**Comment by Wil-B** [comment] 2021-05-25 22:42
In fact my snippet has the user agents commented out.

Yours doesn't work for me either. It gives:
Status: 0
response 
So response is blank. Bizarre.

**Comment by kbuffington** [comment] 2021-05-25 23:31
On my machine I have to set a 'User-Agent' or I get Status: 0. Doesn't seem to matter what the UA is for me though as both of your commented out ones work just fine to give me a response.

readyState = 4 means that the request has completed (doesn't say anything about success or failure).
A status of 0 means that the connection was terminated and no response was received (not even headers).

In this situation the only real reasons this could happen is that the request was blocked by a firewall or some other kind of filtering, or that your program terminated the call before it completed. The last seems unlikely so maybe YT has an IP block on requests it can't verify from you/your region?

Anyway, the problem is at the YT end and doesn't have anything to do with xmlhttp which seems to work just fine.

**Comment by Wil-B** [comment] 2021-05-26 10:49
As far as I can tell there is no ip block, as site can be searched in browsers.

I tried changing to a synchronous request as that gives better error reporting. I tested with your snippet changing: xmlhttp.open(type, url, true) to xmlhttp.open(type, url, false)

The search then throws the following error:

```
ActiveX_Run failed:
ActiveXObject:
  code: 0x80070005
  description: Access is denied.

  source: msxml3.dll

File: <main>
Line: 6, Column: 10
Stack trace:
  makeHttpRequest@<main>:6:10
  @<main>:15:1
```

Whether that's related to YT in my region detecting internet explorer and rejecting the request or some local issue I wouldn't know.

All internet explorer settings are at default.

If it's a local issue then I'll close the topic.

**Comment by kbuffington** [comment] 2021-05-26 14:52
Synchronous I get the same thing:
```
>>>> Status: 200
<!DOCTYPE html><html style="font-size: 10px;font-family: Roboto, Arial, sans-serif;" lang="en" typography typography-spacing><head><meta http-equiv="X-UA-Compatible" content="IE=edge"/><script nonce="fpUSE9fTvr/VvHZuJuD/kg">var ytcfg={d:function(){re...
```

Access is denied sounds like it thinks you're making a CORS request for whatever reason, but I would imagine that all calls made through the ActiveX object would not have CORS issues.

BTW, you mentioned that you had found a workaround. What was it?

In further thinking, one thing that might be helpful would be a method that FSM provides to make these calls itself. The SDK has these functions already, so seems like it wouldn't be too hard to add and then we could all ditch Microsoft.XMLHTTP for good.

**Comment by kbuffington** [comment] 2021-05-26 15:25
A little more investigation. My code as posted seems to fail randomly. Turns out the reason is this:
```
	xmlhttp.send();
	xmlhttp.onreadystatechange = () => {
		if (xmlhttp.readyState == 4) {
			successCB(xmlhttp.responseText);
		}
	};
```
If the response returns very fast (even in an async setting this can happen due to caching) it may get a response before the onreadystatechange handler has been set.

Swapping the order to:
```
	xmlhttp.onreadystatechange = () => {
		if (xmlhttp.readyState == 4) {
			successCB(xmlhttp.responseText);
		}
	};
	xmlhttp.send();
```
...fixes this issue. I don't think that's @Wil-B 's problem, but it's something to be aware of.

**Comment by kbuffington** [comment] 2021-05-28 21:19
Heh, that's a weird not-intuitive HTTP API. Is that why you removed it when starting jscript_panel?

**Comment by marc2k3** [comment] 2021-05-29 00:12
It's a different component forked from the original WSH panel mod. Note the PLUS in the name.

However, a few functions in JScript Panel (and now SMP) did originate from that component.

plman.AddLocations, GdiBitmap SaveAs and utils.MapString I remember. There may be one or two others I've forgotten about.

**Comment by TheQwertiest** [comment] 2022-07-30 11:54
Will be fixed with https://github.com/TheQwertiest/foo_spider_monkey_panel/issues/23, since it will use more modern WinAPI instead of an old ActiveXObject.

**Closed by TheQwertiest** 2022-07-30 11:54 UTC
Labels: enhancement
