### ISSUE TITLE
Mouse over a tooltip: on_mouse_leave event

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#66] opened 2019-03-13 13:17 UTC
Hello!

It look like there is a minor bug when you activate a tooltip below the mouse cursor. SMP assume that the mouse is then out of the panel, and fire an on_mouse_leave event.
Some code to test this behavior below. You'll see that the tooltip appears and disappear immediately. If you changed the tooltip_x_offset, tooltip_y_offset vars to something like 40, the tooltip won't be below the cursor, and so on_mouse_leave won't called, and it doesn't flicker anymore.
```
var m_x = m_y = 0;
var tooltip  = window.CreateTooltip();
var tooltip_activated = false;
tooltip.TrackActivate = true;	
tooltip_x_offset = tooltip_y_offset = -10;

function on_mouse_move(x, y){
	if(m_x==x && m_y==y) return;
	console.log("on_mouse_move")	
	if(!tooltip_activated){
		tooltip.Text = "test";								
		tooltip.Activate();
		tooltip_activated = true;
		tooltip.TrackActivate = true;			
	}		
	tooltip.TrackPosition(x+tooltip_x_offset, y+tooltip_y_offset);						
	m_x = x; m_y = y;	
}
function on_mouse_leave(x, y){
	console.log("on_mouse_leave")		
	tooltip.Deactivate();
	tooltip_activated = false;
}
```

**Comment by Ottodix** [comment] 2019-03-13 14:59
And there also another...maybe not bug, but annoying behavior: in the above code, if you remove the 4 line 
`tooltip.TrackActivate = true; `
then on the first activation of the tooltip, so first on_mouse_move call, it will appears on the default position, even if there is tooltip.TrackActivate = true; and tooltip.TrackPosition() lines inside the on_mouse_move function.

On the second activation of the tooltip (so you move your mouse out of the panel, and back in the panel), it will be then rightly positioned according to the values set by tooltip.TrackPosition(x+tooltip_x_offset, y+tooltip_y_offset);

This means that when you toggle the value of tooltip.TrackActivate, it's not immediately effective

**Comment by marc2k3** [comment] 2019-03-13 17:07
It's very unclear what you're trying to do, especially as the tooltip text never changes and that is a big no-no when calling Activate - you must always check it is different from the existing value.

Here's the original sample from WSH panel mod...

```js
// vi:set ft=javascript ff=dos ts=4 sts=4 sw=4 et:

// ==PREPROCESSOR==
// @name "Tooltip"
// @author "T.P Wang"
// ==/PREPROCESSOR==

// ------------------------------
// --- COMMON FUNCTIONS
// ------------------------------
function RGBA(r, g, b, a) {
    return ((a << 24) | (r << 16) | (g << 8) | (b));
}

function RGB(r, g, b) {
    return (0xff000000 | (r << 16) | (g << 8) | (b));
}

var DT_TOP = 0x00000000;
var DT_CENTER = 0x00000001;
var DT_VCENTER = 0x00000004;
var DT_WORDBREAK = 0x00000010;
var DT_CALCRECT = 0x00000400;
var DT_NOPREFIX = 0x00000800;

// Create a windows tooltip here
// Please do not create more than one tooltip in one panel
var g_tooltip = window.CreateTooltip();
var g_font = gdi.Font("Tahoma", 14);
var g_trackingMouse = false;
var g_oldX, g_oldY;
var ww, wh;


function on_mouse_move(x, y) {
    if (!g_trackingMouse) {
        g_tooltip.Activate();
        g_tooltip.TrackActivate = true;
        g_trackingMouse = true;
    }
    
    // Make sure the position is changed
    if (g_oldX != x || g_oldY != y) {
        g_tooltip.Text = "x:" + x + ", y:" + y;
        g_tooltip.TrackPosition(x + 10, y + 20);
        g_oldX = x;
        g_oldY = y;
    }
}

function on_mouse_leave() {
    g_trackingMouse = false;
    g_tooltip.TrackActivate = false;
}

function on_size() {
    ww = window.Width;
    wh = window.Height;
}

function on_paint(gr) {
    gr.GdiDrawText("Move your mouse", g_font, RGB(0, 0, 0), 0, 0, ww, wh, DT_VCENTER | DT_CENTER | DT_WORDBREAK | DT_CALCRECT | DT_NOPREFIX);
}
```

**Comment by Ottodix** [comment] 2019-03-13 17:36
My code was an example, it doesn't have any real utility. And the tooltip is activated and the tooltip text is set to "test" only once. Then, the TrackPosition() function is called only when the mouse coordinates change. So exactly like your sample, the only difference is the text, which never changes.

This sample have the same kind of bug, the one I was explaining in my second comment: The tooltip is activated only if you 

1. Go over the panel. Then on_mouse_move is called, tooltip is supposed to be activated..but isn't visible.
2. Go out. Then on_mouse_leave is called
3. And go back in the panel. Then the tracking will work, the tooltip will be visible.

In this sample, if you change  `g_tooltip.TrackPosition(x + 10, y + 20);` to ` g_tooltip.TrackPosition(x - 10, y - 10);`
You will see the first bug i was talking about, the tooltip will flicker because the cursor will be above it and on_mouse_leave will be called.

I don't think so but...maybe those bugs exists only on my configuration, I will try on a clean foobar installation.

**Comment by marc2k3** [comment] 2019-03-13 18:58
Well it seems there is no fix for placing the tooltip text behind the mouse pointer. Even this example is adding offsets to prevent exactly what you're doing....

https://docs.microsoft.com/en-us/windows/desktop/controls/implement-tracking-tooltips

I guess a docs update is needed here.

**Comment by TheQwertiest** [comment] 2019-03-14 12:35
AFAIU, there are two *bugs* reported here:
1. Tooltip not activating before triggering `on_mouse_leave`.
2. Tooltip glitches when drawn under cursor.

Regarding bug 1:
Yep, that's a bug in SMP (it works properly in JSP), I'll look into it.

Regarding bug 2:
Seems that it's not a bug, but a limitation of WinAPI.
@marc2k3 Thanks for investigating, will update docs accordingly.

**Comment by Ottodix** [comment] 2019-03-14 13:19
AFAIUYUIPR

**Comment by TheQwertiest** [comment] 2019-03-14 16:39
Should be fixed with the latest build (once it's ready)

**Closed** 2019-03-14 16:38 UTC

**Comment by Ottodix** [comment] 2019-03-14 16:48
ok, thanks

**Comment by Wil-B** [comment] 2019-03-14 18:41
Some tooltips no longer work properly on my device.

g_tooltip.Text seems to truncate text above a certain length & display the truncated text.

Previously g_tooltip.Text displayed & stored the full string.

A consequence of this is that when testing if new text is same as existing g_tooltip.Text, test may say they're different when they're actually the same, resulting in misbehaviour..

I can easily work around it though if this is intended new behaviour.

**Comment by marc2k3** [comment] 2019-03-14 18:48
Yep, already noticed this myself...

https://github.com/marc2k3/smp_2003/commit/62a8b736d938954bfdbca3a532213571463ea198

It's intentional because I peeked at the code in the commit above.

However, JSP has no issue with tooltips over 80 bytes in length...

![Untitled](https://user-images.githubusercontent.com/34617027/54383347-c15be600-4689-11e9-8847-ecaed4e6c05f.png)

**Comment by Wil-B** [comment] 2019-03-14 20:08
Well for comparison DUI album list does not truncate tooltips at 80 characters, and so Library Tree would behave differently.

**Comment by TheQwertiest** [comment] 2019-03-15 09:02
Welp, MSDN **[lied](https://docs.microsoft.com/en-us/windows/desktop/controls/ttm-settoolinfo)** to me >_<
Removed the limit/truncation.
