### ISSUE TITLE
window.NotifyOthers / on_notify_data

### ISSUE THREAD

**Issue by marc2k3** [TheQwertiest/foo_spider_monkey_panel#4] opened 2018-09-20 17:19 UTC
Previously, this supported any kind of object like a handle, image, etc but that no longer works...

Panel 1
```js
var m = fb.GetFocusItem();
window.NotifyOthers("test", m);
```

Panel 2
```js
function on_notify_data(name, info) {
    if (name == "test") console.log(info.Path); // undefined
}
```

Plain strings/numbers/booleans seem to work OK.

I can workaround it as-is but the docs would need updating and it would need marking as a breaking change.

**Comment by TheQwertiest** [comment] 2018-09-20 18:41
Regretfully, I don't think I can fix that...
Full story: each panel is a separate JavaScript context, so transferring data via `NotifyOthers` means transferring data between JS contexts. The problem is that all modern JS engines are rather strict about making such transfers, i.e. you can't just pass the object between contexts. I 'solved' it with a JSON wrapper, which only works for simple parsable objects.

I'll try delving again into SpiderMonkey docs to see how this can be achieved, though I'm afraid that such transfers might incur huge performance penalty.

**Comment by marc2k3** [comment] 2018-09-20 18:47
Don't worry about it - I only use it in my own personal scripts. It's not required for anything I share. Because the only handles I ever pass are part of my library, I can pass a plain text query from one panel specifying the path and subsong index and the other side, I can use fb.GetQueryItems  to get the handle I need.

**Comment by TheQwertiest** [comment] 2018-09-20 19:17
Haha, actually I've just discovered, that it's achievable and not really that hard to do =)

One limitation though: transfered objects should not be stored inside the callee, since it might lead to memory leaks (i.e. soft leaks): they might prevent some GC inside caller context until the object is freed in the callee context); and hard to trace behaviour: the object is shared, so if modified from one panel, it will be modified in all other panels as well

**Comment by TheQwertiest** [comment] 2018-09-20 19:29
Note to self: use JS_WrapValue +  js::NukeCrossCompartmentWrappers

**Comment by marc2k3** [comment] 2018-09-20 19:30
I would actually need to port my heavily modified version of Br3tt's JSplaylist to SMP to even use this so really do put this as the lowest priority. It's unlikely I'll be doing that anytime soon because I'd rather have a play trying to learn the new ES6+ stuff this component supports.

**Closed** 2018-09-20 21:13 UTC
Labels: enhancement
