### ISSUE TITLE
UndoBackup works only for the active playlist

### ISSUE THREAD

**Issue by Ottodix** [TheQwertiest/foo_spider_monkey_panel#77] opened 2019-06-28 10:28 UTC
Hi,

It looks like plman.UndoBackup creates a new backup available through Edit > Undo only for the active playlist.
You can try with the following code. If the line plman.ActivePlaylist = 0; is commented, then no backup available. Otherwise, line uncommented, you can do Edit > Undo, and you then end up with an empty "test_undobackup" playlist.

```
plman.CreatePlaylist(0, "test_undobackup");
plman.UndoBackup(0);
//plman.ActivePlaylist = 0;	
var libraryList = fb.GetLibraryItems();	
plman.InsertPlaylistItems(0, 0, libraryList);
```

I'm trying to create history buttons on my theme, like on a browser. 
Separate questions : do you know a way to check if the Edit > Undo or Edit > Redo commands are grayed ? Like that, i can adapt the look of my history buttons, and make them grayed when there is no backup points backward or forward.

**Comment by TheQwertiest** [comment] 2019-06-28 12:08
> If the line plman.ActivePlaylist = 0; is commented, then no backup available.

I'm calling fb2k API directly([code](https://github.com/TheQwertiest/foo_spider_monkey_panel/blob/d49cb9e3e612803b9b2c28091cd47e60e486b1d9/foo_spider_monkey_panel/js_objects/fb_playlist_manager.cpp#L736)), so it might be actually a fb2k bug.

> do you know a way to check if the Edit > Undo or Edit > Redo commands are grayed 

There is currently no such functionality available.
It's possible to implement the checking for undo/redo actions availability (there is fb2k API for that), but I'm not sure if I want to add such API...

**Comment by Ottodix** [comment] 2019-06-28 12:15
Ok, do you want me to open a post on the support forum myself about that?

About the second question, ok, thanks for the reply!

**Comment by TheQwertiest** [comment] 2019-06-28 12:17
> Ok, do you want me to open a post on the support forum myself about that?

I'll post myself, since it's me who is using fb2k API (possibly incorrectly) =)

> About the second question

It's quite possible, that I'll change my opinion in the future though ;)

**Comment by Ottodix** [comment] 2019-06-28 12:28
> It's quite possible, that I'll change my opinion in the future though ;)

Yep, I act like that myself when people ask about new features on my theme. I usually say "I may do it, but I may not...don't hold your breath", and so far I always ended up coding those features :) That's the endless run of humanity toward improvement which is our jailer :) (poetic thought...)

**Comment by marc2k3** [comment] 2019-07-01 10:30
There is no bug here. If you insert a new playlist at index 0 and add files to it, the actual index of the active playlist will increment by 1 but its state of being the active playlist hasn't changed. The Edit menu is always bound to the active playlist and won't see anything to undo.

**Comment by Ottodix** [comment] 2019-07-01 10:58
AH ok! Thanks marc for the explanation

**Comment by TheQwertiest** [comment] 2019-07-01 10:59
Thanks @marc2k3 !
Closing this issue, since it's not a bug =)
Moved API extension request to a separate issue (#78 ).

**Closed by TheQwertiest** 2019-07-01 10:59 UTC
Labels: API limitation, bug
