### ISSUE TITLE
handle_list.Find() fails sometimes

### ISSUE THREAD

**Issue by Isabelxxx** [TheQwertiest/foo_spider_monkey_panel#126] opened 2021-01-08 22:46 UTC
I have found 1 weird bug while working on a removeDuplicates function by format.

Lets say I check for 2 files, and this becomes true
if (handleA.RawPath == handleB.RawPath)
then I try to find file
idx = handle_list.Find(handleB);

but idx sometimes becomes -1 randomly for iso files. Note it makes no sense since A and B exist and are 2 different handles inside the same list.

 If I execute the same code multiple times, then it works.

								if (handleA.RawPath == handleB.RawPath) {
									let idx = handle_list.Find(handleB); //Needed. Or it would remove all instances of the same handle!
									if (idx != -1) { // It should be redundant, but sometimes Find method fails with DVD-A files!
										let idxcache = idx; //Needed. Or it would remove all instances of the same handle!
										while (idxcache != -1) {
											handle_list.RemoveById(idxcache);
											idxcache = handle_list.Find(handleB);
										}
										handle_list.Insert(idx,handleA); //It was last copy. Revert once to first place.
									}
									else {console.log(handleB);}
									// break; // No need to continue if they were identical
								} else { // Files may be identified as "equal" but be totally different tracks/handles
									let idxA = handle_list.Find(handleA);
									let idxB = handle_list.Find(handleB);
									if (idxB != -1) { // We may have removed A or B before!
										handle_list.Remove(handleB); 
									}

**Comment by Isabelxxx** [comment] 2021-01-08 22:53
Note the else clause should never be executed, but the log says otherwise...

[23:42:32] FbMetadbHandle {FileSize=6221070336, Length=207, Path="H:\Musica_SACD\Pink Floyd\The dark side of the Moon {2011 US DVD-A EMI 50999 029431 2 1}\Pink Floyd TDSOM 2011.iso", RawPath="file://H:\Musica_SACD\Pink Floyd\The dark side of the Moon {2011 US DVD-A EMI 50999 029431 2 1}\Pink Floyd TDSOM 2011.iso", SubSong=131336, ...}
...

**Comment by Isabelxxx** [comment] 2021-01-08 23:19
Just tested this, and I can confirm iso files are somwehat broken. Changing
handle_list.Insert(idx,handleA); //It was last copy. Revert once to first place.
with
if (handleA.RawPath.split('.').pop() != 'iso') {handle_list.Insert(idx,handleA);}
stops the bug on removing duplicates. 
Anyway the find part seems to be broken.

**Comment by TheQwertiest** [comment] 2021-01-15 20:12
Not sure that this is something that I can fix:
- `FbMetadbHandleList` is mapped directly to fb2k internal `metadb_handle_list`.
- `FbMetadbHandle` is mapped directly to fb2k internal `metadb_handle_ptr`.
- `FbMetadbHandleList.Find()` is mapped directly to `metadb_handle_list.find(metadb_handle_ptr)`.

So it looks like it's a fb2k bug.
The only way it could be a SMP bug if `FbMetadbHandleList` is modified somehow before calling `FbMetadbHandleList.Find()`.

**Comment by marc2k3** [comment] 2021-01-16 03:15
I have no idea how ISO files are handled but that SubSong looks suspect to me, If a single file contained 10 tracks, they should be numbered 0-9, not have a value of 131336.

You have to remember that one physical file can have multiple handles and only ones with a matching SubSong would match even though the RawPath check would be true for all handles belonging to that file.

**Comment by TheQwertiest** [comment] 2021-01-16 13:56
>  If a single file contained 10 tracks, they should be numbered 0-9, not have a value of 131336.

It certainly looks suspicious and makes me sure, that it's a fb2k bug.

**Comment by TheQwertiest** [comment] 2021-01-16 13:59
@Isabelxxx can you add a playlistview CUI panel, add a column that displays %subsong% and post a screenshot with this panel?

**Comment by TheQwertiest** [comment] 2021-04-09 13:00
Closing, since it's not caused by SMP.

**Closed by TheQwertiest** 2021-04-09 13:00 UTC
Labels: 3rd-party bug
