### ISSUE TITLE
Excellent benchmarks except sort

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#33] opened 2018-10-26 12:04 UTC
Summary
1) There appears to have been a regression in speed of OrderByRelativePath(), at least on my machine. Can it be fixed?
2) String sort speed is slower than with JSP, at least on my machine. Can it be improved?

More info is below.

I benchmarked library tree. With one of the earlier SMP versions, SMP & JSP initialisation times of the various library tree views were essentially same.

I am pleased to say that in 1.0.4 all the default views (e.g. View by Artist etc) initialise ~1.5 times faster with SMP 1.0.4 compared with JSP (well done!), bar one.

That one is "View by Folder Structure", which now initialises faster in JSP. I pinned it down to a regression in the speed of OrderByRelativePath() which has occurred since version 1.0.3, at least on my machine. Test code:
```
var handle_list = fb.GetLibraryItems();
var t1 = fb.CreateProfiler();
handle_list.OrderByRelativePath();
//var relative_paths = handle_list.GetLibraryRelativePaths();
console.log("OrderByRelativePath Time: " + t1.Time + " msec")
```
The OrderByRelativePath() step in the initialisation of "View by Folder Structure" accounts for >80% of the initialisation time of that view and so its speed has a clear effect. As its a regression since version 1.0.3 may be it can be fixed.

Sometimes library tree uses string sorts, & I noticed certain things that use these were slower in SMP 1.0.4 vs JSP. I pinned this down to the string sort functions running more slowly on SMP 1.0.4 compared with JSP, at least on my machine: e.g. standard string sort was ~6 times slower. As far as I tested number sorts were 2-3 fold faster in SMP 1.0.4 vs JSP, and so the issue seemed specific to string sorts. Test code for string sorts is below. I'm not sure if string sorting speed is something you have control over?
```
var t1 = fb.CreateProfiler();
var A = [];
var ln = 100000
for (var i = 0; i < ln; i++) A.push("Disc " + (Math.round(Math.random() * 20)).toString());

var localeCompareSort_NumHandling = function(a, b) {
    return a.replace(/^\?/,"").replace(/(\d+)/g, function(n) {return ('0000' + n).slice(-5)})
    .localeCompare(
        b.replace(/^\?/,"").replace(/(\d+)/g, function(n) {return ('0000' + n).slice(-5)})
    );
}
    
t1.Reset();
A.sort(localeCompareSort_NumHandling);
console.log("localeCompare String Sort with Number Handling: Time: " + t1.Time + " msec");


A = [];
for (var i = 0; i < ln; i++) A.push("Disc " + (Math.round(Math.random() * 20)).toString());

var strSort_NumHandling = function (a, b) {
    a = a.replace(/^\?/,"").replace(/(\d+)/g, function(n) {return ('0000' + n).slice(-5)});
    b = b.replace(/^\?/,"").replace(/(\d+)/g, function(n) {return ('0000' + n).slice(-5)});
    return a < b ? -1 : a > b ? 1 : 0;
}
    
t1.Reset();
A.sort(strSort_NumHandling);
console.log("Standard String Sort with Number Handling: Time: " + t1.Time + " msec");

A = [];
for (var i = 0; i < ln; i++) A.push("Disc " + (Math.round(Math.random() * 20)).toString());

var localeCompareSort = function(a, b) {
    return a.localeCompare(b);
}
    
t1.Reset();
A.sort(localeCompareSort);
console.log("localeCompare String Sort: Time: " + t1.Time + " msec");


A = [];
for (var i = 0; i < ln; i++) A.push("Disc " + (Math.round(Math.random() * 20)).toString())

var strSort = function (a, b) {
    return a < b ? -1 : a > b ? 1 : 0;
}
    
t1.Reset();
A.sort(strSort);
console.log("Standard String Sort: Time: " + t1.Time + " msec");
```

**Comment by TheQwertiest** [comment] 2018-10-26 13:05
Thanks for the report! 
Since it's a regression from v1.0.3, I'm 99% sure that it can be fixed =)
And I even have the inkling on what might be causing it...

**Comment by TheQwertiest** [comment] 2018-10-29 11:04
>> OrderByRelativePath()

I benchmarked a bit, and it seems that old sort (based on pfc::sort) is faster on randomized arrays (up to 30%) and slower on sorted arrays (up to 15%) than new sort (based on std::sort).

I will return the old sort, since there's no sense sorting already sorted arrays...

**Comment by TheQwertiest** [comment] 2018-10-29 14:01
> standard string sort was ~6 times slower

Confirmed to be a Mozilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1502882
This won't be fixed in SMP anytime time soon though: the bug will be most likely fixed only on the latest Firefox/SpiderMonkey, while SMP uses the latest stable build (ESR60). Unless they port the fix to ESR60, of course.

**Comment by TheQwertiest** [comment] 2018-10-29 16:14
> I will return the old sort, since there's no sense sorting already sorted arrays...

I will not, since I found something MUCH better: https://github.com/tvanslyke/timsort-cpp
Same as pfc::sort on uniformly distributed data and up to 6x faster on partially sorted data (which is usually the case, e.g. tracks in albums).

**Closed** 2018-10-29 19:19 UTC
Labels: performance, regression

**Comment by TheQwertiest** [comment] 2018-10-29 19:22
Should be fixed in the latest build (once it's done building).

**Comment by marc2k3** [comment] 2018-10-29 20:15
It looks like you've broken it because you've removed the `subsong` from the end of the path. This breaks sorting for cuehseets or files with multiple chapters - using `get_relative_path. One physical file can have multiple handles which all return the same path and now you have no way to differentiate them from each other.

**Comment by TheQwertiest** [comment] 2018-10-29 21:12
Oh, I see, should've known that it was there for a reason... Thanks!

**Comment by TheQwertiest** [comment] 2018-10-29 21:49
@marc2k3 : fixed in https://github.com/TheQwertiest/foo_spider_monkey_panel/commit/0968478abbb274729fe910d3f14cd8d260cf8c23

**Comment by Wil-B** [comment] 2018-10-30 12:13
Thanks. Just to confirm that OrderByRelativePath performance is fixed: timsort seems a great find.
