### ISSUE TITLE
ActiveXObject error when dealing with exotic filename encodings

### ISSUE THREAD

**Issue by Wil-B** [TheQwertiest/foo_spider_monkey_panel#54] opened 2019-01-29 11:24 UTC
I wondered if you had any thoughts on [this.](https://hydrogenaud.io/index.php/topic,112913.msg967833.html#new)

What seems to have happened is: 
utils.Glob(folder + "*") > loaded a bunch files from a folder; i.e. the files all existed.

Files were then filtered. Part of that filtering involved using fso to check file parameters.

seongbin obtained error:

ActiveX_Run failed:
ActiveXObject: Error code 0x800a0035

The error code seems to mean fso couldn't find the file (but I'm not sure)???? Since the file was found by utils.Glob(folder + "*") that implies there is a mismatch.

Does this mean there is an issue in the ActiveXObject object handling in SMP?

I might be able to workaround the error by adding an extra check, i.e. using fso to also test if file exists, but then it would fail to load... seongbin also solved it by turning on "Beta: use unicode utf-8 for worldwide language support" in the system locale setting & then the files loaded.

Should users be expected to adjust such settings?

**Comment by TheQwertiest** [comment] 2019-01-29 12:15
> The error code seems to mean fso couldn't find the file (but I'm not sure)

Yup, that's file not found error. Error message will be improved in the next version.

> Does this mean there is an issue in the ActiveXObject object handling in SMP

Not sure at the moment, it might be a limitation imposed `ActiveXObject`/`FileSystemObject`, but we'll see.

Judging by the user report, the problem is triggered by filenames containing Unicode symbols (e.g. kanji), so maybe it was encoded/decoded incorrectly somewhere...

**Comment by TheQwertiest** [comment] 2019-01-29 12:17
Could you, please, provide the failing FSO code, so I could try to reproduce it locally?

**Comment by marc2k3** [comment] 2019-01-29 15:33
You could avoid fso altogether by using:

```js
var path = ...
var size = utils.FileTest(path, "s");
var tmp = utils.FileTest(path, "split");
console.log(tmp[1]); //basename
console.log(tmp[2].substr(1)); // ext - have to use substr because you don't want the period

```

**Comment by Wil-B** [comment] 2019-01-30 12:37
Thanks. It does work, but it seems too slow:

```
read TIME utils.Glob(folder + *):  32  msec // # Files:  74 
filterTime ORIGINAL (fso methods) 95  msec // # Filtered Files 73 
filterTime NEW (FileTest methods) 1408  msec // # Filtered Files 73 
```

The bug also presumably effects any use of fso.FileExists(file) which therefore isn't robust. In some circumstances FileTest could be used instead of fso.FileExists(file), but not if the following action is also using fso since they appear to be giving different answers with certain Unicode symbols.

**Comment by TheQwertiest** [comment] 2019-01-30 13:37
The problem with fso and Unicode will be addressed (since it's working in JSP) once I find the cause.

**Comment by TheQwertiest** [comment] 2019-01-30 14:15
@Wil-B Could you try the nightly build? It should yield better performance with `utils.FileTest`.

**Comment by Wil-B** [comment] 2019-01-30 16:35
`utils.FileTest seems fine now. ` Thanks for the quick fix. 

But I've had some GdiPlus errors. They effect ApplyMask & you should be able to reproduce it with the ApplyMask.js sample.  Not sure if it effects anything else - that's all I spotted -  normal images seemed fine.
```
Error: Spider Monkey Panel v1.1.6-beta+e38e8e6 (ApplyMask by T.P Wang / marc2003)
DrawImage failed:
GdiPlus error: DrawImage failed with error (0x8: WrongState

File: <main>
Line: 28, Column: 9

Stack trace:
  on_paint@<main>:28:9
```

**Comment by marc2k3** [comment] 2019-01-30 17:38
I'm struggling to see how utils.FileTest in "s" was ever an issue in the first place?? It's much faster than than fso...

```js
var test = fb.CreateProfiler("test");
var files = utils.Glob("c:\\windows\\system32\\*.dll");

var total = 0;

for (var i = 0; i < files.length; i++) {
    total += utils.FileTest(files[i], "s");
}

console.log(files.length);
console.log(total);
```

SMP v1.1.5 (before any changes)
```
2493 
1291839854 
Spider Monkey Panel v1.1.5: profiler (test): 66 ms
```

SMP v1.1.6 Beta
```
2493 
1291839854 
Spider Monkey Panel v1.1.6-beta+e38e8e6: profiler (test): 62 ms
```

OK, slight improvement... can't complain...

But fso is much slower...

```js
var test = fb.CreateProfiler("test");
var files = utils.Glob("c:\\windows\\system32\\*.dll");
var fso = new ActiveXObject("Scripting.FileSystemObject");

var total = 0;

for (var i = 0; i < files.length; i++) {
    total += fso.GetFile(files[i]).Size;
}

console.log(files.length);
console.log(total);
```

```
2493 
1291839854 
Spider Monkey Panel v1.1.5: profiler (test): 219 ms
```

fso is quicker on JSP than SMP though - but still much slower than utils.FileTest. 

```
2493
1291839854
JScript Panel v2.2.0.1 (id:66172): initialised in 162 ms
```

Same code - just had to stick `toArray()` on the end of `utils.Glob`

**Comment by Wil-B** [comment] 2019-01-30 17:54
Not sure if this is the reason or not, but the discrepancy I saw between fso & FileTest was only ever on the first run for a particular folder. If the test was repeated on the same folder FileTest was faster than fso. For me it's the first run that matters.

Here is the full set of results before the FileTest change:
```
read TIME utils.Glob(folder + *):  32  msec // # Files:  74 
filterTime ORIGINAL (fso methods) 95  msec // # Filtered Files 73 
filterTime NEW (FileTest methods) 1408  msec // # Filtered Files 73 
filterTime ORIGINAL (fso methods [repeat run]) 16  msec // # Filtered Files 73 
filterTime NEW (FileTest methods [repeat run]) 5  msec // # Filtered Files 73 
```
Any way it's all sorted now.

**Comment by TheQwertiest** [comment] 2019-01-30 18:45
Opening file is much slower than reading it's header. I'm too lazy to measure the performance improvement again (IIRC, it was somewhere around 2.5x), so I'll just leave a link to stackoverflow: https://stackoverflow.com/a/18040026

PS: ActiveX will always be faster in JSP than in SMP, coz I have to wrap it in JS objects, while in JSP ActiveX objects are JS objects themselves (i.e. JScript JavaScript engine uses ActiveX object as a base).

**Comment by sjs-1956** [comment] 2021-01-23 09:40
Back to the original subject...
I have script that compares the artist name to a file name where Wil-B's biography panel writes biog text and then uses the fso to get the modified date of the file. Firstly I used it on my existing files and all worked. I then used musicbrainz to tag the file and it didn't work. The string compare failed  and when I bypassed the compare, the fso failed with the above error message. When I manually changed the artist name, all worked again. It looks as though it's down to the apostrophe character. See below  for ascii dump of both strings. If you need further info please let me know.

This works:
original string=livin' blues - ram jam josey.txt
ascii codes:
#0=0x6c (l)
#1=0x69 (i)
#2=0x76 (v)
#3=0x69 (i)
#4=0x6e (n)
#5=0x27 (')
#6=0x20 ( )
#7=0x62 (b)
#8=0x6c (l)
#9=0x75 (u)
#10=0x65 (e)
#11=0x73 (s)
#12=0x20 ( )
#13=0x2d (-)
#14=0x20 ( )
#15=0x72 (r)
#16=0x61 (a)
#17=0x6d (m)
#18=0x20 ( )
#19=0x6a (j)
#20=0x61 (a)
#21=0x6d (m)
#22=0x20 ( )
#23=0x6a (j)
#24=0x6f (o)
#25=0x73 (s)
#26=0x65 (e)
#27=0x79 (y)
#28=0x2e (.)
#29=0x74 (t)
#30=0x78 (x)
#31=0x74 (t)

This doesn't work:
original string=livin’ blues - ram jam josey.txt
ascii codes:
#0=0x6c (l)
#1=0x69 (i)
#2=0x76 (v)
#3=0x69 (i)
#4=0x6e (n)
#5=0x2019 (’)
#6=0x20 ( )
#7=0x62 (b)
#8=0x6c (l)
#9=0x75 (u)
#10=0x65 (e)
#11=0x73 (s)
#12=0x20 ( )
#13=0x2d (-)
#14=0x20 ( )
#15=0x72 (r)
#16=0x61 (a)
#17=0x6d (m)
#18=0x20 ( )
#19=0x6a (j)
#20=0x61 (a)
#21=0x6d (m)
#22=0x20 ( )
#23=0x6a (j)
#24=0x6f (o)
#25=0x73 (s)
#26=0x65 (e)
#27=0x79 (y)
#28=0x2e (.)
#29=0x74 (t)
#30=0x78 (x)
#31=0x74 (t)

**Comment by TheQwertiest** [comment] 2021-02-06 17:10
@sjs-1956 , can you try running the following code and check if the error reproduces? (mind the root_path)
```js
let root_path = 'x:/';
let path1 = `${root_path}test'.txt`;
let path2 = `${root_path}test\u0027.txt`; // should be the same as path1
let path3 = `${root_path}test\u2019.txt`;

for (path of [path1,path2,path3]) {
    utils.WriteTextFile(path,"test");
}

let fso = new ActiveXObject('Scripting.FileSystemObject');
for (path of [path1,path2,path3]) {
    let file = fso.GetFile(path);
    console.log(`Name: ${file.Name}; size: ${file.Size}; char code: ${file.Name.charCodeAt(4).toString(16)}`);
}
```

**Comment by sjs-1956** [comment] 2021-02-06 17:33
Hi
No errors generated and I see this on the console:

[17:31:56] Name: test'.txt; size: 7; char code: 27
[17:31:56] Name: test'.txt; size: 7; char code: 27
[17:31:56] Name: test’.txt; size: 7; char code: 2019


Regards
Steve Saunders

________________________________

**Comment by sjs-1956** [comment] 2021-02-06 17:38
Hi
Forgot to say I'm using:
Spider Monkey Panel v1.3.2-beta+dd28ed6b by TheQwertiest
Based on JScript Panel by marc2003
Based on WSH Panel Mod by T.P. Wang

Build: 19:12:53, Feb  5 2021
Columns UI SDK Version: 6.5

Regards
Steve Saunders

________________________________

**Comment by TheQwertiest** [comment] 2021-02-06 18:01
But you *do* get `ActiveXObject: Error code 0x800a0035` when handling `u2019`, right?
Can you provide a sample of the code that produces this error, please?

**Comment by TheQwertiest** [comment] 2022-07-30 11:50
Closing the issue. Fell free to reopen it, if the problem persists and there is a repro code available.

**Closed by TheQwertiest** 2022-07-30 11:50 UTC
Labels: bug, need more info
