### ISSUE TITLE
Incorrect relative path handling on Include

### ISSUE THREAD

**Issue by regorxxx** [TheQwertiest/foo_spider_monkey_panel#154] opened 2022-01-20 19:14 UTC
Hi,
I keep getting error reports about relative paths not working properly on 'include' function.
https://github.com/regorxxx/Playlist-Tools-SMP/issues/5

There have been more in private and hydrogen threads. Last time has been with 1.6.1 release.

I know you have been absent due to real life, but this has been a pain in the ass since months. I keep repeating people it's not something I can fix... Any idea?

EDIT: I meant 1.6.1

**Comment by TheQwertiest** [comment] 2022-01-21 12:16
There is additional logging feature included since v1.6.0 in Preferences: Advanced: `log additional information when \`include\` fails` that might help diagnosing the issue.

**Comment by TheQwertiest** [comment] 2022-01-21 12:25
I can't fix it, because I've yet to manage to reproduce it...

**Comment by regorxxx** [comment] 2022-01-21 12:28
> I've yet to manage to reproduce it...
The same! Don't understand what's going on. 
Will ask the users who experienced it to check that additional logging and report.

**Comment by regorxxx** [comment] 2022-01-22 10:21
https://github.com/regorxxx/Playlist-Tools-SMP/issues/5#issuecomment-1018860169

**Comment by TheQwertiest** [comment] 2022-06-15 22:20
Judging by the comments, it doesn't seem that the problem was caused by the component. Closing.

**Closed by TheQwertiest** 2022-06-15 22:20 UTC
Labels: need more info

**Comment by regorxxx** [comment] 2022-06-15 22:28
No idea (?) did not really understand what was going on. XD

Will keep you informed if there are any news about this from any user.

**Comment by regorxxx** [comment] 2022-06-21 17:19
Ok, new info! The issue should be reopened again.

When the advanced pref. at settings for Include logging is enabled, foobar instance crashes if the file is not found. 
So that was the crash the user was experiencing... (and the logging option has been useless all this time)

Arbitrary code:
`
include('a.js');
`

- Setting disabled -> Ok (just panel crash):
And a standard panel crash popup happens:
![image](https://user-images.githubusercontent.com/83307074/174859595-18e6ee35-df23-49f5-b13c-bbbfef5e292f.png)

- Setting enabled-> Foobar crash:
![image](https://user-images.githubusercontent.com/83307074/174859700-cde6f5c0-79ba-4fab-b842-0dd1a970977f.png)

**Comment by TheQwertiest** [comment] 2022-06-24 21:40
crash when using debug output fixed on dev build
